before_install:
- openssl aes-256-cbc -K $encrypted_5b9474172531_key -iv $encrypted_5b9474172531_iv
  -in Dialogflow-prosjektet-80303a8d5040.json.enc -out ../Dialogflow-prosjektet-80303a8d5040.json
  -d

script:
  - ./gradlew assemble
  - ./gradlew appengineStage

deploy:
  provider: gae
  keyfile: "Dialogflow-prosjektet-80303a8d5040.json.enc"
  project: "dialogflow-cogito"
  config: "build/staged-app"
  only: master

