dist: xenial
language: java

before_install:
- openssl aes-256-cbc -K $encrypted_5b9474172531_key -iv $encrypted_5b9474172531_iv
  -in Dialogflow-prosjektet-80303a8d5040.json.enc -out Dialogflow-prosjektet-80303a8d5040.json
  -d

env:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

install:
  # If the SDK is not already cached, download it and unpack it
  - rm -R $HOME/google-cloud-sdk
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
    curl https://sdk.cloud.google.com | bash;
    fi
  - export PATH=$HOME/google-cloud-sdk/bin:$PATH
  - gcloud components install app-engine-java
  - gcloud auth activate-service-account --key-file=Dialogflow-prosjektet-80303a8d5040.json

script:
  - ./gradlew build test assemble appengineDeploy

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/google-cloud-sdk/