dist: xenial
language: java

before_install:
- openssl aes-256-cbc -K $encrypted_5b9474172531_key -iv $encrypted_5b9474172531_iv
  -in Dialogflow-prosjektet-80303a8d5040.json.enc -out ../Dialogflow-prosjektet-80303a8d5040.json
  -d

install:
  - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
  - apt update
  - apt install google-cloud-sdk google-cloud-sdk-app-engine-java

script:
  - ./gradlew build test assemble appengineStage

deploy:
  provider: gae
  keyfile: "Dialogflow-prosjektet-80303a8d5040.json.enc"
  project: "dialogflow-cogito"
  default: true
  config: "build/staged-app"
  only: master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
