dist: xenial
language: java

before_install:
- openssl aes-256-cbc -K $encrypted_5b9474172531_key -iv $encrypted_5b9474172531_iv
  -in Dialogflow-prosjektet-80303a8d5040.json.enc -out ../Dialogflow-prosjektet-80303a8d5040.json
  -d

install:
  - gcloud components install app-engine-java

script:
  - ./gradlew build test assemble appengineStage

deploy:
  provider: gae
  keyfile: "Dialogflow-prosjektet-80303a8d5040.json.enc"
  project: "dialogflow-cogito"
  default: true
  config: "build/staged-app"
  only: master

